
CREATE TABLE[dbo].[TB_FUNCIONARIO]
(
	[I_COD_FUNCIONARIO] INT IDENTITY(1, 1) NOT NULL,
	[S_NM_FUNCIONARIO] VARCHAR(35) NOT NULL,
	[S_CPF_FUNCIONARIO] VARCHAR(14) NOT NULL,
	[S_CNH_FUNCIONARIO] VARCHAR(14),
	[S_CEL_FUNCIONARIO] VARCHAR(15) NOT NULL,
	[I_PER_FUNCIONARIO] INT NOT NULL,
	[S_CID_FUNCIONARIO] VARCHAR(35) NOT NULL,
	[S_BAI_FUNCIONARIO] VARCHAR(35) NOT NULL,
	[S_END_FUNCIONARIO] VARCHAR(40) NOT NULL,
	PRIMARY KEY CLUSTERED ([I_COD_FUNCIONARIO] ASC)
);

CREATE TABLE[dbo].[TB_ITEMEQUIPE]
(
	[I_COD_ITEMEQUIPE] INT IDENTITY(1, 1) NOT NULL,
	[I_COD_EQUIPE] INT NOT NULL,
	[I_COD_FUNCIONARIO] INT NOT NULL,
	[S_EQUIC_EQUIPE] VARCHAR(35) NOT NULL,
	PRIMARY KEY CLUSTERED ([I_COD_ITEMEQUIPE] ASC),
	FOREIGN KEY ([I_COD_EQUIPE]) REFERENCES [dbo].[TB_EQUIPE] ([I_COD_EQUIPE]),
	FOREIGN KEY ([I_COD_FUNCIONARIO]) REFERENCES [dbo].[TB_FUNCIONARIO] ([I_COD_FUNCIONARIO])

);





CREATE TABLE[dbo].[TB_SERVICO]
(
	[I_COD_SERVICO] INT IDENTITY(1, 1) NOT NULL,
	[I_COD_AGENDAMENTO] INT NOT NULL,
	[I_COD_EQUIPE] INT NOT NULL,
	[S_TIP_SERVICO] VARCHAR(35) NOT NULL,
	PRIMARY KEY CLUSTERED ([I_COD_SERVICO] ASC),
	FOREIGN KEY ([I_COD_AGENDAMENTO]) REFERENCES [dbo].[TB_AGENDAMENTO] ([I_COD_AGENDAMENTO]),
	FOREIGN KEY ([I_COD_EQUIPE]) REFERENCES [dbo].[TB_EQUIPE] ([I_COD_EQUIPE])
);